env_name: 'development'
domain_name: 'expenses.com'
hostname: 'dev.expenses.com'

ip_addresses:
  app:
    expense: '192.168.30.4'
  services: '192.168.31.4'

box:
  define: 'sam-development'
  name: 'bento/ubuntu-22.04'
  box_version: '202510.26.0'
  base: 'samanga-local-cloud-parallels-base'
  check_update: true

mysql_server:
  username: awsmysql
  password: ''
  database:
    name: sam

network:
  forward_agent: true
